# Required for the QA lint-twig to work
framework:
    test: true
    secret: 'dummy'
    http_method_override: false
    handle_all_throwables: true
    validation:
        email_validation_mode: html5
    php_errors:
        log: true
