sonata_admin:
    templates:
        layout: '@SmartSonata/standard_layout.html.twig'
        user_block: '@SmartSonata/block/user.html.twig'
    # Remove default mosaic as customer never really want default behavior
    show_mosaic_button: false
    options:
        default_translation_domain: 'admin'
    default_admin_services:
        label_translator_strategy: 'sonata.admin.label.strategy.underscore'
    security:
        handler:   Smart\SonataBundle\Security\Handler\SmartSecurityHandler
    extensions:
        admin.extension.encode_password:
            uses:
                - Smart\SonataBundle\Entity\User\UserTrait

# Global Timezone Config
# https://stackoverflow.com/a/26469662
# https://symfony.com/doc/current/bundles/SonataAdminBundle/reference/field_types.html
sonata_intl:
    timezone:
        locales:
            fr:    Europe/Paris

# Set alice_data_fixtures no_purge mode and disable other drivers than orm
fidry_alice_data_fixtures:
    default_purge_mode: no_purge
    db_drivers:
        doctrine_orm: true
        doctrine_mongodb_odm: false
        doctrine_phpcr_odm: false
        eloquent_orm: false

yokai_security_token:
    tokens:
        reset_password:
            duration: +1 month

nelmio_alice:
    locale: fr_FR

smart_sonata:
    emails:
        - admin.security.forgot_password
        - admin.security.account_creation
