services:
  admin.extension.action_delete:
    class: Smart\SonataBundle\Admin\Extension\ActionExtension
    arguments:
      - delete
    tags:
      - { name: sonata.admin.extension, global: true }
  admin.extension.action_edit:
    class: Smart\SonataBundle\Admin\Extension\ActionExtension
    arguments:
      - edit
    tags:
      - { name: sonata.admin.extension, global: true }
  admin.extension.action_view:
    class: Smart\SonataBundle\Admin\Extension\ActionExtension
    arguments:
      - view
    tags:
      - { name: sonata.admin.extension, global: true }
