name: CI

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [
          # '8.2', Not supported due to SYMFONY_PHPUNIT_VERSION set 12.2 requiring php 8.3
          '8.3',
          '8.4'
        ]
    container:
      image: ghcr.io/${{ github.repository_owner }}/symfony-docker:php${{ matrix.php }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -   name: Checkout repository
          uses: actions/checkout@v4
      -   name: Configure GitHub token for Composer
          run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
      - name: Check PHP Version
        run: php -v

      # —— Composer 🧙‍️ —————————————————————————————————————————————————————————
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install
        run: make install

      # —— Tests 🧪 ————————————————————————————————————————————————————————————
      - name: Phpunit tests
        run: make coverage

      # —— QA ✔️‍️ ———————————————————————————————————————————————————————————————
      - name: Qualimetry
        run: make qa
